services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres-nextjs-dashboard
    restart: unless-stopped
    environment:
      POSTGRES_USER: nextjs
      POSTGRES_PASSWORD: e40db
      POSTGRES_DB: dashboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: